### ISSUE TITLE
implements employee api

### ISSUE THREAD

**Issue by tktcorporation** [tktcorporation/typescript-isolating-the-domain#3]
# Tasks

## POST

- [x] register
  - [x] test
  - [x] implements
- [ ] register name
  - [ ] test
  - [ ] implements
- [ ] register mail address
  - [ ] test
  - [ ] implements
- [ ] register phone number
  - [ ] test
  - [ ] implements

## GET

- [ ] employee list
  - [ ] test
  - [ ] implements
- [ ] employee by primary key
  - [ ] test
  - [ ] implements
